# Generated by Django 6.1 on 2026-08-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_google_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('auth0', 'Auth0')], default='email', max_length=20),
        ),
    ]
